apiVersion: apps/v1
kind: Deployment
metadata:
  name: okteuioy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okteuioy
  template:
    metadata:
      labels:
        app: okteuioy
    spec:
      containers:
      - image: okteto.dev/okteuioy:latest
        name: okteuioy
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "a64c6d5c-9511-4673-bb8c-fc63b1528f32"
        - name: Vless_Path
          value: "/fghf666"
        - name: Vmess_UUID
          value: "a64c6d5c-9511-4673-bb8c-fc63b1528f32"
        - name: Vmess_Path
          value: "/fghf666"
        - name: Share_Path
          value: "/v2link"
